# Generated by Django 5.2.6 on 2025-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('APPROVER', 'Approver'), ('ADMIN', 'Admin')], default='USER', max_length=50),
        ),
    ]
