# Generated by Django 5.2.6 on 2025-09-25 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(verbose_name='รายละเอียดกิจกรรม')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่จัดกิจกรรม')),
                ('slots_available', models.PositiveIntegerField(verbose_name='จำนวนที่รับสมัคร')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name='รูปภาพกิจกรรม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ไม่อนุมัติ')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
