# Generated by Django 5.2.6 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(verbose_name='รายละเอียดกิจกรรม')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่จัดกิจกรรม')),
                ('category', models.CharField(choices=[('จิตอาสาด้านสาธารณประโยชน์', 'จิตอาสาด้านสาธารณประโยชน์'), ('จิตอาสาด้านการศึกษา', 'จิตอาสาด้านการศึกษา'), ('จิตอาสาด้านสุขภาพ', 'จิตอาสาด้านสุขภาพ'), ('จิตอาสาด้านสิ่งแวดล้อม', 'จิตอาสาด้านสิ่งแวดล้อม'), ('จิตอาสาด้านภัยพิบัติและบรรเทาทุกข์', 'จิตอาสาด้านภัยพิบัติและบรรเทาทุกข์'), ('จิตอาสาด้านศาสนาและวัฒนธรรม', 'จิตอาสาด้านศาสนาและวัฒนธรรม'), ('จิตอาสาด้านเทคโนโลยีและสื่อสาร', 'จิตอาสาด้านเทคโนโลยีและสื่อสาร'), ('จิตอาสาด้านเยาวชนและเด็ก', 'จิตอาสาด้านเยาวชนและเด็ก'), ('จิตอาสาด้านสัตว์และสิ่งมีชีวิต', 'จิตอาสาด้านสัตว์และสิ่งมีชีวิต'), ('กิจกรรมรณรงค์/ประกวด', 'กิจกรรมรณรงค์/ประกวด')], max_length=100, verbose_name='ประเภทกิจกรรม')),
                ('slots_available', models.PositiveIntegerField(verbose_name='จำนวนที่รับสมัคร')),
                ('fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='ค่าใช้จ่าย (บาท)')),
                ('allow_register', models.BooleanField(default=True, verbose_name='เปิดให้ลงทะเบียนผ่านระบบ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name='รูปภาพกิจกรรม')),
                ('schedule', models.FileField(blank=True, null=True, upload_to='schedules/', verbose_name='กำหนดการ (ไฟล์)')),
                ('map_lat', models.FloatField(blank=True, null=True, verbose_name='ละติจูด')),
                ('map_lng', models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด')),
                ('create_group', models.BooleanField(default=False, verbose_name='สร้างกลุ่มสำหรับกิจกรรมนี้')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='ซ่อนโพสต์')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='ลบแบบซ่อน')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ไม่อนุมัติ')], default='PENDING', max_length=10, verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'โพสต์กิจกรรม',
                'verbose_name_plural': 'โพสต์กิจกรรมทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
