# Generated by Django 5.2.6 on 2025-10-15 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'โพสต์กิจกรรม', 'verbose_name_plural': 'โพสต์กิจกรรมทั้งหมด'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('จิตอาสาด้านสาธารณประโยชน์', 'จิตอาสาด้านสาธารณประโยชน์'), ('จิตอาสาด้านการศึกษา', 'จิตอาสาด้านการศึกษา'), ('จิตอาสาด้านสุขภาพ', 'จิตอาสาด้านสุขภาพ'), ('จิตอาสาด้านสิ่งแวดล้อม', 'จิตอาสาด้านสิ่งแวดล้อม'), ('จิตอาสาด้านภัยพิบัติและบรรเทาทุกข์', 'จิตอาสาด้านภัยพิบัติและบรรเทาทุกข์'), ('จิตอาสาด้านศาสนาและวัฒนธรรม', 'จิตอาสาด้านศาสนาและวัฒนธรรม'), ('จิตอาสาด้านเทคโนโลยีและสื่อสาร', 'จิตอาสาด้านเทคโนโลยีและสื่อสาร'), ('จิตอาสาด้านเยาวชนและเด็ก', 'จิตอาสาด้านเยาวชนและเด็ก'), ('จิตอาสาด้านสัตว์และสิ่งมีชีวิต', 'จิตอาสาด้านสัตว์และสิ่งมีชีวิต'), ('กิจกรรมรณรงค์/ประกวด', 'กิจกรรมรณรงค์/ประกวด')], default=1, max_length=100, verbose_name='ประเภทกิจกรรม'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='map_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AddField(
            model_name='post',
            name='map_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AddField(
            model_name='post',
            name='schedule',
            field=models.FileField(blank=True, null=True, upload_to='schedules/', verbose_name='กำหนดการ (ไฟล์)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_posts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้างโพสต์'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
    ]
