# Generated by Django 5.2.6 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slots_available',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0 = ไม่จำกัดจำนวน', verbose_name='จำนวนที่รับสมัคร'),
        ),
    ]
