# Generated by Django 5.2.6 on 2025-11-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_likes_post_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_register',
            field=models.BooleanField(default=True, verbose_name='เปิดให้ลงทะเบียนผ่านระบบ'),
        ),
        migrations.AddField(
            model_name='post',
            name='create_group',
            field=models.BooleanField(default=False, verbose_name='สร้างกลุ่มสำหรับกิจกรรมนี้'),
        ),
        migrations.AddField(
            model_name='post',
            name='fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ค่าใช้จ่าย (บาท)'),
        ),
    ]
