# Generated by Django 5.2.6 on 2026-02-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_slots_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slots_available',
            field=models.PositiveIntegerField(verbose_name='จำนวนที่รับสมัคร'),
        ),
    ]
