# Generated by Django 5.2.6 on 2025-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_allow_register_post_create_group_post_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='ลบแบบซ่อน'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='ซ่อนโพสต์'),
        ),
    ]
