# Generated by Django 6.0 on 2025-12-24 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0005_post_is_deleted_post_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='report_evidence/posts/', verbose_name='รูปหลักฐาน (ถ้ามี)')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('RESOLVED', 'จัดการแล้ว'), ('REJECTED', 'ไม่เข้าข่าย')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='จัดการเมื่อ')),
                ('action_note', models.CharField(blank=True, default='', max_length=255, verbose_name='ผลการจัดการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='รายงานเมื่อ')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการรายงาน')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='post.post', verbose_name='โพสต์ที่ถูกรายงาน')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน')),
            ],
            options={
                'verbose_name': 'รายงานโพสต์',
                'verbose_name_plural': 'รายงานโพสต์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='report_evidence/users/', verbose_name='รูปหลักฐาน (ถ้ามี)')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('RESOLVED', 'จัดการแล้ว'), ('REJECTED', 'ไม่เข้าข่าย')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='จัดการเมื่อ')),
                ('action_note', models.CharField(blank=True, default='', max_length=255, verbose_name='ผลการจัดการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='รายงานเมื่อ')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการรายงาน')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีที่ถูกรายงาน')),
            ],
            options={
                'verbose_name': 'รายงานบัญชี',
                'verbose_name_plural': 'รายงานบัญชี',
                'ordering': ['-created_at'],
            },
        ),
    ]
