# Generated by Django 5.2.6 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='report_evidence/posts/', verbose_name='รูปหลักฐาน (ถ้ามี)')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('RESOLVED', 'จัดการแล้ว'), ('REJECTED', 'ไม่เข้าข่าย')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='จัดการเมื่อ')),
                ('action_note', models.CharField(blank=True, default='', max_length=255, verbose_name='ผลการจัดการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='รายงานเมื่อ')),
            ],
            options={
                'verbose_name': 'รายงานโพสต์',
                'verbose_name_plural': 'รายงานโพสต์',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผล')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='report_evidence/users/', verbose_name='รูปหลักฐาน (ถ้ามี)')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('RESOLVED', 'จัดการแล้ว'), ('REJECTED', 'ไม่เข้าข่าย')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='จัดการเมื่อ')),
                ('action_note', models.CharField(blank=True, default='', max_length=255, verbose_name='ผลการจัดการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='รายงานเมื่อ')),
            ],
            options={
                'verbose_name': 'รายงานบัญชี',
                'verbose_name_plural': 'รายงานบัญชี',
                'ordering': ['-created_at'],
            },
        ),
    ]
