# Generated by Django 5.2.6 on 2026-02-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approver', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการรายงาน'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='post.post', verbose_name='โพสต์ที่ถูกรายงาน'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดการรายงาน'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รายงาน'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='บัญชีที่ถูกรายงาน'),
        ),
    ]
