# Generated by Django 5.2.6 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], max_length=10)),
                ('current_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_channel', models.CharField(help_text='เช่น Facebook, IG, Line ID', max_length=255)),
                ('chronic_disease', models.CharField(blank=True, max_length=255)),
                ('food_allergy', models.CharField(blank=True, max_length=255)),
                ('drug_allergy', models.CharField(blank=True, max_length=255)),
                ('field_ability', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], help_text='ความสามารถในการเข้าร่วมกิจกรรมภาคสนาม', max_length=1)),
                ('consent_personal_data', models.BooleanField(help_text='ยินยอมให้ใช้ข้อมูลส่วนตัวเพื่อวัตถุประสงค์ในกิจกรรม')),
                ('consent_terms', models.BooleanField(help_text='ยอมรับเงื่อนไขและข้อกำหนดของกิจกรรม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'สมัครแล้ว'), ('CANCEL_PENDING', 'รอยืนยันยกเลิก'), ('CANCELED', 'ยกเลิกแล้ว')], default='ACTIVE', max_length=20)),
                ('cancel_reason', models.CharField(blank=True, choices=[('NOT_AVAILABLE', 'วันเวลานั้นไม่สะดวกแล้ว'), ('HEALTH', 'มีปัญหาสุขภาพกระทันหัน'), ('OTHER', 'อื่นๆระบุ')], default='', max_length=20)),
                ('cancel_reason_other', models.CharField(blank=True, default='', max_length=255)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_undo_until', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
