# Generated by Django 5.2.6 on 2025-11-19 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_post_likes_post_saves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('นาย', 'นาย'), ('นางสาว', 'นางสาว'), ('นาง', 'นาง')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], max_length=10)),
                ('current_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_channel', models.CharField(help_text='เช่น Facebook, IG, Line ID', max_length=255)),
                ('chronic_disease', models.CharField(blank=True, max_length=255)),
                ('food_allergy', models.CharField(blank=True, max_length=255)),
                ('drug_allergy', models.CharField(blank=True, max_length=255)),
                ('field_ability', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], help_text='ความสามารถในการเข้าร่วมกิจกรรมภาคสนาม', max_length=1)),
                ('consent_personal_data', models.BooleanField(help_text='ยินยอมให้ใช้ข้อมูลส่วนตัวเพื่อวัตถุประสงค์ในกิจกรรม')),
                ('consent_terms', models.BooleanField(help_text='ยอมรับเงื่อนไขและข้อกำหนดของกิจกรรม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='post.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
