# Generated by Django 5.2.6 on 2026-02-04 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_register', '0002_activityreview'),
        ('post', '0005_post_is_deleted_post_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('NOT_AVAILABLE', 'วันเวลานั้นไม่สะดวกแล้ว'), ('HEALTH', 'มีปัญหาสุขภาพกระทันหัน'), ('OTHER', 'อื่นๆระบุ')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='cancel_reason_other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='cancel_undo_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'สมัครแล้ว'), ('CANCEL_PENDING', 'รอยืนยันยกเลิก'), ('CANCELED', 'ยกเลิกแล้ว')], default='ACTIVE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='activityregistration',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_user_post_registration'),
        ),
    ]
