# Generated by Django 5.2.6 on 2026-02-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_register', '0002_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to='post.post'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='activityregistration',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_user_post_registration'),
        ),
        migrations.AlterUniqueTogether(
            name='activityreview',
            unique_together={('post', 'user')},
        ),
    ]
