# Generated by Django 5.2.6 on 2026-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_register', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
