# Generated by Django 5.2.6 on 2026-02-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REGISTER_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้สมัคร)'), ('SAVED_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้บันทึก)'), ('OWNER_STATUS_REMINDER', 'แจ้งเตือนสถานะผู้สมัคร (ผู้สร้างกิจกรรม)'), ('OWNER_FULL', 'แจ้งเตือนกิจกรรมเต็ม (ผู้สร้างกิจกรรม)'), ('POST_UPDATED', 'แจ้งเตือนเมื่อโพสต์มีการเปลี่ยนแปลง'), ('SYSTEM', 'ระบบ')], default='SYSTEM', max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_date', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'post', 'trigger_date'), name='uniq_user_kind_post_triggerdate')],
            },
        ),
    ]
