# Generated by Django 5.2.6 on 2026-02-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('REGISTER_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้สมัคร)'), ('SAVED_REMINDER', 'แจ้งเตือนก่อนกิจกรรม (ผู้บันทึก)'), ('OWNER_STATUS_REMINDER', 'แจ้งเตือนสถานะผู้สมัคร (ผู้สร้างกิจกรรม)'), ('OWNER_FULL', 'แจ้งเตือนกิจกรรมเต็ม (ผู้สร้างกิจกรรม)'), ('POST_UPDATED', 'แจ้งเตือนเมื่อโพสต์มีการเปลี่ยนแปลง'), ('SYSTEM', 'ระบบ')], default='SYSTEM', max_length=40),
        ),
    ]
